//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingPost.EzyParcels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EbayAndBulkUploadTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EbayAndBulkUploadTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SingPost.EzyParcels.EbayAndBulkUploadTemplate", typeof(EbayAndBulkUploadTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/N,First Name,Middle Name,Last Name,Address 1,Address 2,City,State,Postcode,Country,Contact No,Tracking Number,Cust Reference No,Weight per Article (gm),Length (cm),Height (cm),Width (cm),Declared Currency,Declared Value,Item Description,HS code,Insured (Yes/No),Insured Currency,Insured value,Content Category,To be selected for Priority and Registered Plus (Undelivery),COD (Cash On Delivery),COD Currency,COD Value
        ///,Exception.
        /// </summary>
        internal static string BulkUploadDownloadTemplate {
            get {
                return ResourceManager.GetString("BulkUploadDownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///                                                 &lt;GetSessionIDRequest xmlns=&quot;urn:ebay:apis:eBLBaseComponents&quot;&gt;
        ///                                                    &lt;RuName&gt;@ebayAppRuName&lt;/RuName&gt;
        ///                                                 &lt;/GetSessionIDRequest&gt;.
        /// </summary>
        internal static string ebaySessionInitRequestXml {
            get {
                return ResourceManager.GetString("ebaySessionInitRequestXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [S/N],[Last Name],[Middle Name],[First Name],[Address 1],[Address 2],[City],[State],[Postcode],[Country],[Contact No],[Tracking Number],[Cust Reference No],[Weight per Article (gm)],[Declared Currency],[Declared Value],[Item Description],[HS code],[Insured (Yes/No)],[Insured Currency],[Insured value],[To be selected for Registered and Standards (CN22)].
        /// </summary>
        internal static string EZYPEPITemplate {
            get {
                return ResourceManager.GetString("EZYPEPITemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [S/N],[Last Name],[Middle Name],[First Name],[Address 1],[Address 2],[City],[State],[Postcode],[Country],[Contact No],[Tracking Number],[Cust Reference No],[Weight per Article (gm)],[Declared Currency],[Declared Value],[Item Description],[HS code],[Insured (Yes/No)],[Insured Currency],[Insured value],[To be selected for Priority and Registered Plus (Undelivery)],[To be selected for Priority and Registered Plus (Custom)].
        /// </summary>
        internal static string EZYPPITemplate {
            get {
                return ResourceManager.GetString("EZYPPITemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [S/N],[Middle Name],[Last Name],[First Name],[Address 1],[Address 2],[City],[State],[Postcode],[Country],[Contact No],[Tracking Number],[Cust Reference No],[Weight per Article (gm)],[Declared Currency],[Declared Value],[Item Description],[HS code],[Insured (Yes/No)],[Insured currency],[Insured value],[To be selected for Registered and Standards (CN22)].
        /// </summary>
        internal static string EZYPRITemplate {
            get {
                return ResourceManager.GetString("EZYPRITemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [S/N],[Last Name],[Middle Name],[First Name],[Address 1],[Address 2],[City],[State],[Postcode],[Country],[Contact No],[Tracking Number],[Cust Reference No],[Weight per Article (gm)],[Declared Currency],[Declared Value],[Item Description],[HS code],[Insured (Yes/No)],[Insured Currency],[Insured value],[To be selected for Priority and Registered Plus (Undelivery)],[To be selected for Priority and Registered Plus (Custom)].
        /// </summary>
        internal static string EZYPRPITemplate {
            get {
                return ResourceManager.GetString("EZYPRPITemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [S/N],[Last Name],[Middle Name],[First Name],[Address 1],[Address 2],[City],[State],[Postcode],[Country],[Contact No],[Cust Reference No],[Weight per Article (gm)],[Declared Currency],[Declared Value ],[Item Description],[HS code],[Insured (Yes/No)],[Insured Currency],[Insured value],[To be selected for Registered and Standards (CN22)].
        /// </summary>
        internal static string EZYPSITemplate {
            get {
                return ResourceManager.GetString("EZYPSITemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///                                        &lt;FetchTokenRequest xmlns=&quot;urn:ebay:apis:eBLBaseComponents&quot;&gt;
        ///                                            &lt;SessionID&gt;@ebaySessionID&lt;/SessionID&gt;
        ///                                        &lt;/FetchTokenRequest&gt;.
        /// </summary>
        internal static string FetchTokenRequest {
            get {
                return ResourceManager.GetString("FetchTokenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///                                    &lt;GetOrdersRequest xmlns=&quot;urn:ebay:apis:eBLBaseComponents&quot;&gt;
        ///                                        &lt;RequesterCredentials&gt;
        ///                                            &lt;eBayAuthToken&gt;@ebaytokenTogetOrder&lt;/eBayAuthToken&gt;
        ///                                        &lt;/RequesterCredentials&gt;
        ///                                        &lt;DetailLevel&gt;ReturnAll&lt;/DetailLevel&gt;
        ///                                        &lt;NumberOfDays&gt;@maxDaysInPast&lt;/Nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOrdersRequest {
            get {
                return ResourceManager.GetString("GetOrdersRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///                                                      &lt;GetUserRequest xmlns=&quot;urn:ebay:apis:eBLBaseComponents&quot;&gt;
        ///                                                        &lt;RequesterCredentials&gt;
        ///                                &lt;eBayAuthToken&gt;@authTokenForEbay&lt;/eBayAuthToken&gt;
        ///                                                        &lt;/RequesterCredentials&gt;
        ///                                                      &lt;/GetUserRequest&gt;.
        /// </summary>
        internal static string GetUserRequest {
            get {
                return ResourceManager.GetString("GetUserRequest", resourceCulture);
            }
        }
    }
}
